dist: xenial
language: python
python: 3.7

install:
  - pip install flake8 kodi-addon-checker

before_script:
- git config core.quotepath false

# command to run our tests
script:
  - flake8 ./ --statistics --show-source --ignore=E501 --exclude=croniter.py,*/dropbox/* # check python structure against flake8 tests, ignore long lines
  - kodi-addon-checker --branch=matrix --allow-folder-id-mismatch